(() => {
  "use strict";
  const KEY="site_settings_v1", FORMS=["4-3-3","4-2-3-1","4-3-1-2","4-4-2","3-4-3","3-5-2"];
  const DEF={notifySubscribers:true,formations:FORMS,labels:{stillPlaying:"Still Playing",lastCuts:"Last Cuts",lightConsiderations:"Light Considerations"},site:{text_hero_title:"Half Space",text_nav_country:"21st Century country XIs",text_nav_club:"Club XIs",text_nav_continental:"21st Century Continental XIs",text_nav_rankings:"Player Rankings"}};
  const read=(k,d)=>typeof window.getData==="function"?window.getData(k,d):d;
  function get(){const s=read(KEY,{})||{},site={...DEF.site,...(s.site||{})};Object.keys(site).forEach(k=>site[k]=read(k,site[k]));return{notifySubscribers:s.notifySubscribers!==false,formations:s.formations||FORMS,definitions:s.definitions||{},teamFormations:s.teamFormations||{},labels:{...DEF.labels,...(s.labels||{})},site};}
  const label=k=>get().labels[k]||DEF.labels[k];
  function apply(){const s=get(),n=document.getElementById("hsPublishNotify");if(n&&!document.getElementById("hsPublishingModal")?.classList.contains("open"))n.checked=s.notifySubscribers;document.querySelectorAll(".hm-tier-title").forEach(el=>{for(const k of Object.keys(DEF.labels))if(el.textContent.trim()===DEF.labels[k])el.textContent=s.labels[k];});}
  function ui(){if(document.getElementById("hsSettingsModal"))return;const m=document.createElement("div");m.id="hsSettingsModal";m.innerHTML=`<div class="hs-set-card" role="dialog" aria-modal="true"><button id="hsSetClose" aria-label="Close">✕</button><h2>Site Settings</h2><p>Labels, XI choices, and publishing defaults stored with the site.</p><form id="hsSetForm"><h3>Site labels</h3>${Object.entries({text_hero_title:"Site name",text_nav_rankings:"Rankings navigation",text_nav_country:"Country XIs navigation",text_nav_club:"Club XIs navigation",text_nav_continental:"Continental XIs navigation"}).map(([k,v])=>`<label>${v}<input name="${k}"></label>`).join("")}<h3>Ranking labels</h3>${Object.entries({stillPlaying:"Still playing",lastCuts:"Last cuts",lightConsiderations:"Light considerations"}).map(([k,v])=>`<label>${v}<input name="${k}"></label>`).join("")}<h3>XI formations</h3><div id="hsFormationChecks" class="hs-set-checks"></div><p><button type="button" id="hsAddFormation">+ Add formation</button></p><h3>Publishing</h3><label><input type="checkbox" name="notifySubscribers"> Start “Notify subscribers” checked</label><footer><span id="hsSetStatus"></span><button type="submit">Save settings</button></footer></form></div>`;document.body.appendChild(m);const st=document.createElement("style");st.textContent=`#hsSettingsModal{position:fixed;inset:0;z-index:100400;display:none;align-items:center;justify-content:center;background:rgba(5,15,9,.76);padding:1rem;font-family:var(--sans,sans-serif)}#hsSettingsModal.open{display:flex}.hs-set-card{position:relative;width:min(680px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:10px;padding:1.4rem}.hs-set-card>button{position:absolute;right:1rem;top:1rem}.hs-set-card h2{margin:0;color:var(--accent)}.hs-set-card p{color:#666;font-size:.8rem}.hs-set-card h3{margin:1.1rem 0 .5rem;color:var(--accent);font-size:.78rem;text-transform:uppercase}.hs-set-card form>label{display:grid;grid-template-columns:190px 1fr;align-items:center;gap:.6rem;margin:.45rem 0;font-size:.78rem}.hs-set-card input[type=text],.hs-set-card input:not([type]){padding:.55rem;border:1px solid #ccc}.hs-set-checks{display:flex;flex-wrap:wrap;gap:.7rem}.hs-set-card footer{display:flex;gap:1rem;align-items:center;justify-content:flex-end;margin-top:1rem}.hs-set-card footer span{margin-right:auto;font-size:.76rem;color:var(--accent)}.hs-set-card footer button{padding:.65rem 1rem;background:var(--accent);color:#fff;border:0;border-radius:4px}@media(max-width:600px){.hs-set-card form>label{grid-template-columns:1fr}}`;document.head.appendChild(st);m.onclick=e=>{if(e.target===m)close()};document.getElementById("hsSetClose").onclick=close;document.getElementById("hsSetForm").onsubmit=save;document.getElementById("hsAddFormation").onclick=addFormation;}
  function renderForms(){const s=get();document.getElementById("hsFormationChecks").innerHTML=[...FORMS,...Object.keys(s.definitions)].map(x=>`<label><input type="checkbox" name="formation" value="${x}" ${s.formations.includes(x)?"checked":""}> ${x}</label>`).join("");}
  function open(){if(window.HSPermissions?.can?.("manageSettings")===false)return;ui();const s=get(),f=document.getElementById("hsSetForm");Object.entries({...s.site,...s.labels}).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});renderForms();f.elements.notifySubscribers.checked=s.notifySubscribers;document.getElementById("hsSettingsModal").classList.add("open");}
  function addFormation(){const name=prompt("Formation name (example: 3-4-2-1):")?.trim();if(!name)return;const raw=prompt("Enter pitch rows from goalkeeper to forwards. Separate rows with | and positions with commas.","GK | RCB,CB,LCB | RM,CM,CM,LM | RAM,LAM | ST");if(!raw)return;const rows=raw.split("|").map(r=>r.split(",").map(x=>x.trim()).filter(Boolean)).filter(r=>r.length);if(rows.flat().length!==11){alert("A formation must contain exactly 11 positions.");return}const s=get();s.definitions[name]={rows:rows.map(r=>r.map(label=>({pos:label,label}))),positions:rows.flat().map(label=>({pos:label,label}))};s.formations=[...new Set([...s.formations,name])];window.setData(KEY,s);renderForms();}
  function configureTeam(name){const s=get(),all=[...FORMS,...Object.keys(s.definitions)],current=s.teamFormations[name]||s.formations;const raw=prompt(`Allowed formations for ${name} (comma-separated):`,current.join(", "));if(raw===null)return;const chosen=raw.split(",").map(x=>x.trim()).filter(x=>all.includes(x));if(!chosen.length){alert("Choose at least one valid formation.");return}s.teamFormations[name]=chosen;window.setData(KEY,s);window.HSAutosave?.schedule?.();alert(`Allowed formations saved for ${name}.`);}
  function close(){document.getElementById("hsSettingsModal")?.classList.remove("open");}
  function save(e){e.preventDefault();const f=e.currentTarget,formations=[...f.querySelectorAll('[name="formation"]:checked')].map(x=>x.value),status=document.getElementById("hsSetStatus");if(!formations.length){status.textContent="Choose at least one formation.";return}const old=get(),s={...old,notifySubscribers:f.elements.notifySubscribers.checked,formations,labels:Object.fromEntries(Object.keys(DEF.labels).map(k=>[k,f.elements[k].value.trim()||DEF.labels[k]])),site:Object.fromEntries(Object.keys(DEF.site).map(k=>[k,f.elements[k].value.trim()||DEF.site[k]]))};window.setData(KEY,s);Object.entries(s.site).forEach(([k,v])=>window.setData(k,v));window.HSAutosave?.schedule?.();apply();status.textContent="Saved. Publish Changes when ready.";}
  window.HSSettings={get,label,getDefinitions:()=>get().definitions,getFormations:()=>get().formations,allowedFor:(name,all)=>get().teamFormations[name]||get().formations.filter(x=>all.includes(x)),configureTeam,open,close,apply};document.addEventListener("DOMContentLoaded",apply);
})();
